version: '3.8'

services:
  zhdanov-pw:
    build: .
    container_name: zhdanov-pw
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      
      # HTTP роутер (авторедирект на HTTPS, если не настроен глобально в Traefik)
      - "traefik.http.routers.zhdanov-http.rule=Host(`zhdanov.pw`) || Host(`www.zhdanov.pw`)"
      - "traefik.http.routers.zhdanov-http.entrypoints=web"
      - "traefik.http.routers.zhdanov-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # HTTPS роутер
      - "traefik.http.routers.zhdanov-https.rule=Host(`zhdanov.pw`) || Host(`www.zhdanov.pw`)"
      - "traefik.http.routers.zhdanov-https.entrypoints=websecure"
      - "traefik.http.routers.zhdanov-https.tls=true"
      - "traefik.http.routers.zhdanov-https.tls.certresolver=myresolver"
      
      # Внутренний порт контейнера Nginx
      - "traefik.http.services.zhdanov-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    name: proxy
    external: true
